In [67]:
from mmengine import Registry
# scope 表示注册器的作用域，如果不设置，默认为包名，例如在 mmdetection 中，它的 scope 为 mmdet
ACTIVATION = Registry('activation', scope='mmengine')

In [68]:
import torch.nn as nn
import torch

# 使用注册器管理模块
@ACTIVATION.register_module()
class Sigmoid(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, x):
        print('call Sigmoid.forward')
        x = torch.sigmoid(x)
        return x

@ACTIVATION.register_module()
class ReLU(nn.Module):
    def __init__(self, inplace=False):
        super().__init__()

    def forward(self, x):
        print('call ReLU.forward')
        x = torch.relu(x)
        return x

@ACTIVATION.register_module()
class Softmax(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, x):
        print('call Softmax.forward')
        x = torch.softmax(x)
        return x

In [69]:
print(ACTIVATION.module_dict)


{'Sigmoid': <class '__main__.Sigmoid'>, 'ReLU': <class '__main__.ReLU'>, 'Softmax': <class '__main__.Softmax'>}


In [70]:
import torch
input = torch.Tensor([-1, 1])

act_cfg = dict(type='Sigmoid')
activation = ACTIVATION.build(act_cfg)
output = activation(input)
# call Sigmoid.forward
print(output)
# tensor([0.0159, 0.0815])

call Sigmoid.forward
tensor([0.2689, 0.7311])


In [72]:
input = torch.Tensor([-1, 1])

act_cfg = dict(type='ReLU', inplace=True)
activation = ACTIVATION.build(act_cfg)
output = activation(input)
# call Sigmoid.forward
print(output)
# tensor([0.0159, 0.0815])

call ReLU.forward
tensor([0., 1.])
